import * as Diff2Html from 'diff2html';

const diff = '--- .tmp/packages/chalk/3.0.0/package/package.json\t1985-10-26 01:15:00.000000000 -0700\n+++ .tmp/packages-from-source/chalk/3.0.0/package/package.json\t1985-10-26 01:15:00.000000000 -0700\n@@ -1,63 +1,63 @@\n {\n-\t\"name\": \"chalk\",\n-\t\"version\": \"3.0.0\",\n-\t\"description\": \"Terminal string styling done right\",\n-\t\"license\": \"MIT\",\n-\t\"repository\": \"chalk/chalk\",\n-\t\"main\": \"source\",\n-\t\"engines\": {\n-\t\t\"node\": \">=8\"\n-\t},\n-\t\"scripts\": {\n-\t\t\"test\": \"xo && nyc ava && tsd\",\n-\t\t\"bench\": \"matcha benchmark.js\"\n-\t},\n-\t\"files\": [\n-\t\t\"source\",\n-\t\t\"index.d.ts\"\n-\t],\n-\t\"keywords\": [\n-\t\t\"color\",\n-\t\t\"colour\",\n-\t\t\"colors\",\n-\t\t\"terminal\",\n-\t\t\"console\",\n-\t\t\"cli\",\n-\t\t\"string\",\n-\t\t\"str\",\n-\t\t\"ansi\",\n-\t\t\"style\",\n-\t\t\"styles\",\n-\t\t\"tty\",\n-\t\t\"formatting\",\n-\t\t\"rgb\",\n-\t\t\"256\",\n-\t\t\"shell\",\n-\t\t\"xterm\",\n-\t\t\"log\",\n-\t\t\"logging\",\n-\t\t\"command-line\",\n-\t\t\"text\"\n-\t],\n-\t\"dependencies\": {\n-\t\t\"ansi-styles\": \"^4.1.0\",\n-\t\t\"supports-color\": \"^7.1.0\"\n-\t},\n-\t\"devDependencies\": {\n-\t\t\"ava\": \"^2.4.0\",\n-\t\t\"coveralls\": \"^3.0.7\",\n-\t\t\"execa\": \"^3.2.0\",\n-\t\t\"import-fresh\": \"^3.1.0\",\n-\t\t\"matcha\": \"^0.7.0\",\n-\t\t\"nyc\": \"^14.1.1\",\n-\t\t\"resolve-from\": \"^5.0.0\",\n-\t\t\"tsd\": \"^0.7.4\",\n-\t\t\"xo\": \"^0.25.3\"\n-\t},\n-\t\"xo\": {\n-\t\t\"rules\": {\n-\t\t\t\"unicorn/prefer-string-slice\": \"off\",\n-\t\t\t\"unicorn/prefer-includes\": \"off\"\n-\t\t}\n-\t}\n+  \"name\": \"chalk\",\n+  \"version\": \"3.0.0\",\n+  \"description\": \"Terminal string styling done right\",\n+  \"license\": \"MIT\",\n+  \"repository\": \"chalk/chalk\",\n+  \"main\": \"source\",\n+  \"engines\": {\n+    \"node\": \">=8\"\n+  },\n+  \"scripts\": {\n+    \"test\": \"xo && nyc ava && tsd\",\n+    \"bench\": \"matcha benchmark.js\"\n+  },\n+  \"files\": [\n+    \"source\",\n+    \"index.d.ts\"\n+  ],\n+  \"keywords\": [\n+    \"color\",\n+    \"colour\",\n+    \"colors\",\n+    \"terminal\",\n+    \"console\",\n+    \"cli\",\n+    \"string\",\n+    \"str\",\n+    \"ansi\",\n+    \"style\",\n+    \"styles\",\n+    \"tty\",\n+    \"formatting\",\n+    \"rgb\",\n+    \"256\",\n+    \"shell\",\n+    \"xterm\",\n+    \"log\",\n+    \"logging\",\n+    \"command-line\",\n+    \"text\"\n+  ],\n+  \"dependencies\": {\n+    \"ansi-styles\": \"^4.1.0\",\n+    \"supports-color\": \"^7.1.0\"\n+  },\n+  \"devDependencies\": {\n+    \"ava\": \"^2.4.0\",\n+    \"coveralls\": \"^3.0.7\",\n+    \"execa\": \"^3.2.0\",\n+    \"import-fresh\": \"^3.1.0\",\n+    \"matcha\": \"^0.7.0\",\n+    \"nyc\": \"^14.1.1\",\n+    \"resolve-from\": \"^5.0.0\",\n+    \"tsd\": \"^0.7.4\",\n+    \"xo\": \"^0.25.3\"\n+  },\n+  \"xo\": {\n+    \"rules\": {\n+      \"unicorn/prefer-string-slice\": \"off\",\n+      \"unicorn/prefer-includes\": \"off\"\n+    }\n+  }\n }\n' +
'--- .tmp/packages/cli-boxes/2.2.1/package/package.json\t1985-10-26 01:15:00.000000000 -0700\n+++ .tmp/packages-from-source/cli-boxes/2.2.1/package/package.json\t1985-10-26 01:15:00.000000000 -0700\n@@ -1,42 +1,42 @@\n {\n-\t\"name\": \"cli-boxes\",\n-\t\"version\": \"2.2.1\",\n-\t\"description\": \"Boxes for use in the terminal\",\n-\t\"license\": \"MIT\",\n-\t\"repository\": \"sindresorhus/cli-boxes\",\n-\t\"funding\": \"https://github.com/sponsors/sindresorhus\",\n-\t\"author\": {\n-\t\t\"name\": \"Sindre Sorhus\",\n-\t\t\"email\": \"sindresorhus@gmail.com\",\n-\t\t\"url\": \"https://sindresorhus.com\"\n-\t},\n-\t\"engines\": {\n-\t\t\"node\": \">=6\"\n-\t},\n-\t\"scripts\": {\n-\t\t\"test\": \"xo && ava && tsd\"\n-\t},\n-\t\"files\": [\n-\t\t\"index.js\",\n-\t\t\"index.d.ts\",\n-\t\t\"boxes.json\"\n-\t],\n-\t\"keywords\": [\n-\t\t\"cli\",\n-\t\t\"box\",\n-\t\t\"boxes\",\n-\t\t\"terminal\",\n-\t\t\"term\",\n-\t\t\"console\",\n-\t\t\"ascii\",\n-\t\t\"unicode\",\n-\t\t\"border\",\n-\t\t\"text\",\n-\t\t\"json\"\n-\t],\n-\t\"devDependencies\": {\n-\t\t\"ava\": \"^1.4.1\",\n-\t\t\"tsd\": \"^0.7.2\",\n-\t\t\"xo\": \"^0.24.0\"\n-\t}\n+  \"name\": \"cli-boxes\",\n+  \"version\": \"2.2.1\",\n+  \"description\": \"Boxes for use in the terminal\",\n+  \"license\": \"MIT\",\n+  \"repository\": \"sindresorhus/cli-boxes\",\n+  \"funding\": \"https://github.com/sponsors/sindresorhus\",\n+  \"author\": {\n+    \"name\": \"Sindre Sorhus\",\n+    \"email\": \"sindresorhus@gmail.com\",\n+    \"url\": \"https://sindresorhus.com\"\n+  },\n+  \"engines\": {\n+    \"node\": \">=6\"\n+  },\n+  \"scripts\": {\n+    \"test\": \"xo && ava && tsd\"\n+  },\n+  \"files\": [\n+    \"index.js\",\n+    \"index.d.ts\",\n+    \"boxes.json\"\n+  ],\n+  \"keywords\": [\n+    \"cli\",\n+    \"box\",\n+    \"boxes\",\n+    \"terminal\",\n+    \"term\",\n+    \"console\",\n+    \"ascii\",\n+    \"unicode\",\n+    \"border\",\n+    \"text\",\n+    \"json\"\n+  ],\n+  \"devDependencies\": {\n+    \"ava\": \"^1.4.1\",\n+    \"tsd\": \"^0.7.2\",\n+    \"xo\": \"^0.24.0\"\n+  }\n }\n';

document.addEventListener('DOMContentLoaded', () => {
  const el = document.createElement('div');

  const parsedDiffs = Diff2Html.parse(diff, {
    drawFileList: true,
    matching: 'lines',
    outputFormat: 'side-by-side',
  });
  
  for (const parsedDiff of parsedDiffs) {
    parsedDiff.oldName = parsedDiff.oldName.replace(/^\.tmp/, '');
    parsedDiff.newName = parsedDiff.newName.replace(/^\.tmp/, '');
  }

  el.innerHTML = Diff2Html.html(parsedDiffs, {
    drawFileList: true,
    matching: 'lines',
    outputFormat: 'side-by-side',
  });
  document.body.append(el);
});
